name: CI

on: 
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs: 
  build-and-test: 
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with: 
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        env: 
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: npm run build

      - name: Run Jest tests
        run: npm test

      - name: Upload coverage report
        if: success()
        uses: actions/upload-artifact@v4
        with: 
          name: coverage-report
          path: coverage/
